$modelname "props_foliage/jastian_hoxxes_azure_voidbasket.mdl"
$body static_prop "jastian_hoxxes_azure_voidbasket.smd"
$staticprop
$surfaceprop no_decal
$cdmaterials "models/props_foliage"
$sequence BindPose "jastian_hoxxes_azure_voidbasket.smd"
$collisionmodel "jastian_hoxxes_azure_voidbasket_collision.smd"
$opaque
$keyvalues
{
	particles
	{
		effect
		{
			name "jastian_hoxxes_azure_voidbasket"
			attachment_type "follow_origin"
		}
	}
}
